name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_debug_apk:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Rename APK
        run: mv app/build/outputs/apk/debug/*.apk app/fbcookie-debug.apk

      - name: Archive APK
        uses: actions/upload-artifact@v3
        with:
          name: FBCookie-Debug
          path: app/fbcookie-debug.apk

  build_release_apk: 
    name: Build Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Upload keystore
        uses: actions/upload-artifact@v3
        with:
          name: keystore
          path: app/marvin-J.jks 

      - name: Download keystore
        uses: actions/download-artifact@v3
        with:
          name: keystore

      - name: Build release APK
        run: ./gradlew assembleRelease \
          -Pandroid.signingConfigs.release.storeFile=marvin-J.jks \
          -Pandroid.signingConfigs.release.storePassword=${{ secrets.KEYSTORE_PASSWORD }} \
          -Pandroid.signingConfigs.release.keyAlias=${{ secrets.KEY_ALIAS }} \
          -Pandroid.signingConfigs.release.keyPassword=${{ secrets.KEY_PASSWORD }}

      - name: Rename APK
        run: mv app/build/outputs/apk/release/*.apk app/fbcookie-release.apk

      - name: Archive APK
        uses: actions/upload-artifact@v3
        with:
          name: FBCookie-Release
          path: app/fbcookie-release.apk
