name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_debug_apk:
    name: Build Debug APK
    runs-on: ubuntu-latest
    env:
      TELEGRAM_CHAT_ID: 5068018361
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Rename APK
        run: mv app/build/outputs/apk/debug/*.apk app/fbcookie-debug.apk

      - name: Send Telegram notification with Debug APK
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "🔨 Debug Build Completed\n\nCommit: $(git log -1 --pretty=%B)\nBranch: ${{ github.ref_name }}\nCommit SHA: ${{ github.sha }}\n"
          document: app/fbcookie-debug.apk

  build_release_apk:
    name: Build Release APK
    runs-on: ubuntu-latest
    env:
      TELEGRAM_CHAT_ID: 5068018361
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Rename APK
        run: mv app/build/outputs/apk/release/*.apk app/fbcookie-release.apk

      - name: Send Telegram notification with Release APK
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "📦 Release Build Completed\n\nCommit: $(git log -1 --pretty=%B)\nBranch: ${{ github.ref_name }}\nCommit SHA: ${{ github.sha }}\n"
          document: app/fbcookie-release.apk